name: Build and Test Wheels, Publish on Release

on:
  push:
    branches: [ main, dev ]
  release:
    types: [ published ] 

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU (for ARM builds)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_MACOS: auto arm64

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fijit
    permissions:
      id-token: write

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v3

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1